// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_htc_viu_In : Valve.VR.SteamVR_Action_List
    {
        
        public Valve.VR.SteamVR_Action_Boolean viu_press_00;
        
        public Valve.VR.SteamVR_Action_Boolean viu_press_01;
        
        public Valve.VR.SteamVR_Action_Boolean viu_press_02;
        
        public Valve.VR.SteamVR_Action_Boolean viu_press_03;
        
        public Valve.VR.SteamVR_Action_Boolean viu_press_04;
        
        public Valve.VR.SteamVR_Action_Boolean viu_press_05;
        
        public Valve.VR.SteamVR_Action_Boolean viu_press_06;
        
        public Valve.VR.SteamVR_Action_Boolean viu_press_07;
        
        public Valve.VR.SteamVR_Action_Boolean viu_press_31;
        
        public Valve.VR.SteamVR_Action_Boolean viu_press_32;
        
        public Valve.VR.SteamVR_Action_Boolean viu_press_33;
        
        public Valve.VR.SteamVR_Action_Boolean viu_press_34;
        
        public Valve.VR.SteamVR_Action_Boolean viu_touch_00;
        
        public Valve.VR.SteamVR_Action_Boolean viu_touch_01;
        
        public Valve.VR.SteamVR_Action_Boolean viu_touch_02;
        
        public Valve.VR.SteamVR_Action_Boolean viu_touch_03;
        
        public Valve.VR.SteamVR_Action_Boolean viu_touch_04;
        
        public Valve.VR.SteamVR_Action_Boolean viu_touch_05;
        
        public Valve.VR.SteamVR_Action_Boolean viu_touch_06;
        
        public Valve.VR.SteamVR_Action_Boolean viu_touch_07;
        
        public Valve.VR.SteamVR_Action_Boolean viu_touch_31;
        
        public Valve.VR.SteamVR_Action_Boolean viu_touch_32;
        
        public Valve.VR.SteamVR_Action_Boolean viu_touch_33;
        
        public Valve.VR.SteamVR_Action_Boolean viu_touch_34;
        
        public Valve.VR.SteamVR_Action_Single viu_axis_0x;
        
        public Valve.VR.SteamVR_Action_Single viu_axis_0y;
        
        public Valve.VR.SteamVR_Action_Single viu_axis_1x;
        
        public Valve.VR.SteamVR_Action_Single viu_axis_1y;
        
        public Valve.VR.SteamVR_Action_Single viu_axis_2x;
        
        public Valve.VR.SteamVR_Action_Single viu_axis_2y;
        
        public Valve.VR.SteamVR_Action_Single viu_axis_3x;
        
        public Valve.VR.SteamVR_Action_Single viu_axis_3y;
        
        public Valve.VR.SteamVR_Action_Single viu_axis_4x;
        
        public Valve.VR.SteamVR_Action_Single viu_axis_4y;
        
        public Valve.VR.SteamVR_Action_Vector2 viu_axis_0xy;
        
        public Valve.VR.SteamVR_Action_Vector2 viu_axis_1xy;
        
        public Valve.VR.SteamVR_Action_Vector2 viu_axis_2xy;
        
        public Valve.VR.SteamVR_Action_Vector2 viu_axis_3xy;
        
        public Valve.VR.SteamVR_Action_Vector2 viu_axis_4xy;
    }
}
